package com.xlh.distribute.transaction.demo.xa.db2.model;

public class Xa2 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xa_2.id
     *
     * @mbg.generated Sun Dec 20 11:30:25 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xa_2.name
     *
     * @mbg.generated Sun Dec 20 11:30:25 CST 2020
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xa_2.id
     *
     * @return the value of xa_2.id
     *
     * @mbg.generated Sun Dec 20 11:30:25 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xa_2.id
     *
     * @param id the value for xa_2.id
     *
     * @mbg.generated Sun Dec 20 11:30:25 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xa_2.name
     *
     * @return the value of xa_2.name
     *
     * @mbg.generated Sun Dec 20 11:30:25 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xa_2.name
     *
     * @param name the value for xa_2.name
     *
     * @mbg.generated Sun Dec 20 11:30:25 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}