package com.xlh.distribute.transaction.local.msg.demo.xa.db2.dao;

import com.xlh.distribute.transaction.local.msg.demo.xa.db2.model.Xa2;
import com.xlh.distribute.transaction.local.msg.demo.xa.db2.model.Xa2Example;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface Xa2Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xa_2
     *
     * @mbg.generated Sun Dec 20 11:30:25 CST 2020
     */
    long countByExample(Xa2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xa_2
     *
     * @mbg.generated Sun Dec 20 11:30:25 CST 2020
     */
    int deleteByExample(Xa2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xa_2
     *
     * @mbg.generated Sun Dec 20 11:30:25 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xa_2
     *
     * @mbg.generated Sun Dec 20 11:30:25 CST 2020
     */
    int insert(Xa2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xa_2
     *
     * @mbg.generated Sun Dec 20 11:30:25 CST 2020
     */
    int insertSelective(Xa2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xa_2
     *
     * @mbg.generated Sun Dec 20 11:30:25 CST 2020
     */
    List<Xa2> selectByExample(Xa2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xa_2
     *
     * @mbg.generated Sun Dec 20 11:30:25 CST 2020
     */
    Xa2 selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xa_2
     *
     * @mbg.generated Sun Dec 20 11:30:25 CST 2020
     */
    int updateByExampleSelective(@Param("record") Xa2 record, @Param("example") Xa2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xa_2
     *
     * @mbg.generated Sun Dec 20 11:30:25 CST 2020
     */
    int updateByExample(@Param("record") Xa2 record, @Param("example") Xa2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xa_2
     *
     * @mbg.generated Sun Dec 20 11:30:25 CST 2020
     */
    int updateByPrimaryKeySelective(Xa2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xa_2
     *
     * @mbg.generated Sun Dec 20 11:30:25 CST 2020
     */
    int updateByPrimaryKey(Xa2 record);
}
