package com.xlh.distribute.transaction.local.msg.demo.db1.dao;

import com.xlh.distribute.transaction.local.msg.demo.db1.model.PaymentMsg;
import com.xlh.distribute.transaction.local.msg.demo.db1.model.PaymentMsgExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PaymentMsgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_msg
     *
     * @mbg.generated Sat Dec 26 20:19:26 CST 2020
     */
    long countByExample(PaymentMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_msg
     *
     * @mbg.generated Sat Dec 26 20:19:26 CST 2020
     */
    int deleteByExample(PaymentMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_msg
     *
     * @mbg.generated Sat Dec 26 20:19:26 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_msg
     *
     * @mbg.generated Sat Dec 26 20:19:26 CST 2020
     */
    int insert(PaymentMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_msg
     *
     * @mbg.generated Sat Dec 26 20:19:26 CST 2020
     */
    int insertSelective(PaymentMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_msg
     *
     * @mbg.generated Sat Dec 26 20:19:26 CST 2020
     */
    List<PaymentMsg> selectByExample(PaymentMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_msg
     *
     * @mbg.generated Sat Dec 26 20:19:26 CST 2020
     */
    PaymentMsg selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_msg
     *
     * @mbg.generated Sat Dec 26 20:19:26 CST 2020
     */
    int updateByExampleSelective(@Param("record") PaymentMsg record, @Param("example") PaymentMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_msg
     *
     * @mbg.generated Sat Dec 26 20:19:26 CST 2020
     */
    int updateByExample(@Param("record") PaymentMsg record, @Param("example") PaymentMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_msg
     *
     * @mbg.generated Sat Dec 26 20:19:26 CST 2020
     */
    int updateByPrimaryKeySelective(PaymentMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_msg
     *
     * @mbg.generated Sat Dec 26 20:19:26 CST 2020
     */
    int updateByPrimaryKey(PaymentMsg record);
}
